### PR TITLE
SpamAssassin: Restart imscp_panel after disable/enable

### PR DESCRIPTION
**Pull request by Backdraft007**

### CODE REVIEW

**Comment by nuxwin** [comment]
Hello,

Why you're doing this exactly in that plugin? Because that plugin provide a plugin for roundcube? In such a case, you should restart the imscp_panel service only if the roundcube plugin for spamassassin is installed ;)

**Comment by Backdraft007** [comment]
Hi,
I have the same behavior in this plugin, so I think it should be implemented. Am I wrong?

**Comment by nuxwin** [comment]
Sure, your fix is ok but you shoudl restart the imscp_panel service only if the webmail roundcube is here.

For instance:

```perl
sub enable
{
	my $self = shift;

	my $rs = $self->_postfixConfig('configure');
	return $rs if $rs;

	if('Roundcube' ~~ [ split ',', $main::imscpConfig{'WEBMAIL_PACKAGES'} ]) {
		$rs = $self->_setRoundcubePlugin('add');
		return $rs if $rs;
	}

	$self->_schedulePostfixRestart();
	
	iMSCP::Service->getInstance()->restart('imscp_panel');

	0;
}
```

Should be

```perl
sub enable
{
	my $self = shift;

	my $rs = $self->_postfixConfig('configure');
	return $rs if $rs;

	if('Roundcube' ~~ [ split ',', $main::imscpConfig{'WEBMAIL_PACKAGES'} ]) {
		$rs = $self->_setRoundcubePlugin('add');
		return $rs if $rs;

		iMSCP::Service->getInstance()->restart('imscp_panel');
	}

	$self->_schedulePostfixRestart();

	0;
}
```

Do you understand me here?

**Comment by Backdraft007** [comment]
Ah yes. OK. Sorry. Forget my pull request.

**Comment by nuxwin** [comment]
You can just modify and PR again ;) Once done, I'll merge. Thank you for your contributions ;)

**Pull request closed without merging**
