### PR TITLE
Mailman

### PR DESCRIPTION
**Pull request by svenjantzen**
add i-mscp 1.2.3 support

### CODE REVIEW

**Comment by nuxwin** [comment]
@svenjantzen 

You surely mean: 1.2.11 (1.0.1 API version mean 1.2.11)

The problem here is that I cannot see the changes you made. I'll get the PR and do a diff.

**Comment by svenjantzen** [comment]
Yes i mean 1.2.11.

Because the diff to the old version 0.0.3, sorry for my mistake i'm new on github.

**Comment by nuxwin** [comment]
No grave. You you give me a little overivew about changes ?

**Comment by svenjantzen** [comment]
no problem.

mailman.pm:
i change the command "$file->copyFile" into the "execute (cp...)" on line 78, 146, 233, 249.

Add "de_DE" language

Add config.php to set default language for mailman in mm_cfg.py. Also add in mailman.pm line 89 to set this value.

**Comment by nuxwin** [comment]
@svenjantzen 

Ok, I'll review your PR this week-end and release a new version.
Thank you for your contribution.

**Comment by svenjantzen** [comment]
@nuxwin 
i hope now you can see the changes that i made.

**Comment by nuxwin** [comment]
Mailman plugin has been fully rewritten. New version will comes soon.

**Pull request closed without merging**
