### PR TITLE
Added German Translation

### PR DESCRIPTION
**Pull request by gOOvER**

### CODE REVIEW

**Comment by Ninos** [comment]
I'll fix some translations and merge it tonight :-)

**Comment by gOOvER** [comment]
Which Part is wrong?? I see not really a Bad Translation.

**Comment by nuxwin** [comment]
At both:

Please wait a bit since some string will be changed ;)

**Comment by Ninos** [comment]
Ah @gOOvER in the second commit you fixed them :D @nuxwin just give us your ok then :)

**Comment by nuxwin** [comment]
Sure ;)

**Comment by gOOvER** [comment]
@nuxwin @Ninos  :thumbsup: :thumbsup: :thumbsup:

**Pull request merged**
