### PR TITLE
Integrated automatic_addressbook - added files and function to manage sql requests.

### PR DESCRIPTION
**Pull request by theqkash**

### CODE REVIEW

**Comment by nuxwin** [comment]
@Ninos 
Please don't merge this PR.

@theqkash Please make this plugin optional by adding a parameter in the config.php plugin configuration file and making needed change in the backend (Perl side).

Thank you.

**Comment by theqkash** [comment]
@nuxwin I have no knowledge about Perl at all. All what I can do, I have done.

**Comment by nuxwin** [comment]
So, you're not able to maintain an i-MSCP plugins... So, we will not integrate that plugin.

**Comment by theqkash** [comment]
@nuxin As you wish. In future just write on forum that you expect full service when setting up the plug-in, then I won't need to waste time preparing something, then what will go into the trash. ;-)

**Comment by Ninos** [comment]
@theqkash just add `automatic_addressbook_plugin` before `calendar_plugin` in /backend/RoundcubePlugins.pm on line 340.

After that add following before `calendar_plugin` in config.php on line 31:
```// Automatic addressbook plugin adds contacts automatically to the Roundcube addressbook.
    'automatic_addressbook_plugin'                   => 'yes', // YES to enable (default), NO to disable```

**Comment by Ninos** [comment]
AND DON'T FORGET TO TEST (change yes to no, change no to yes, remove plugin and install again with no instead of yes...)

**Comment by theqkash** [comment]
@Ninos thanks, but I'm not able to do it now. 
I just don't know how all this stuff works in i-MSCP, I know that this plugin works well when I set it manually, and I think that some people would need it. That's all the reason I have proposed it. I'm still unsure if anything I would made in i-MSCP code would work, I just don't want to break anything, that's why I have left it how I have left, sorry.

**Comment by Ninos** [comment]
I've asked in forum which are also interested into having this plugin into RoundcubePlugins. If there are some other guys I'll implement it.

**Comment by theqkash** [comment]
@Ninos, Thank you.

I've done some mistake that I have set this thing in one server out of 15 which I'm managing now. Once I've done that, people have wanted to setup it in another server...
Some big Polish hosting companies have set up this thing in the past, clients who was there want it because it's just some standard feature from mail software like Thunderbird. 
It's just automatically adding all mails with whom we was having any contact to some custom addressbook. IMO, that's some kind of standard feature for mail software we use nowadays.

This is why I've tried to help it. Maybe it's not the best help you have ever, but I think that this one is better than nothing :-P

**Comment by Ninos** [comment]
np, I'll just wait feedback of our community

**Comment by theqkash** [comment]
Maybe in future I'll be able to set in up from beginning to the end, but now I'm only an admin. 😞

**Pull request closed without merging**
