### PR TITLE
Updated Dutch translations

### PR DESCRIPTION
**Pull request by theemstra**

### CODE REVIEW

**Comment by Ninos** [comment]
Please contact the plugin author of the roundcube plugin pop3fetcher. After it's in his repository I'll also add it here. (Just let me know)

**Comment by theemstra** [comment]
Copy, will submit to maintainer of that project

**Comment by nuxwin** [comment]
We are unable to contact the upstream plugin author so I merge it. We will have to pay attention on next upstream source update ;)

**Comment by theemstra** [comment]
Cheers

**Pull request merged**
