### PR TITLE
Fixed for Roundcube 1.2+

### PR DESCRIPTION
**Pull request by theqkash**
imap_connect is deprecated and should be changed to make it work

### CODE REVIEW

**Comment by Ninos** [comment]
Please fix in upstream version:
https://github.com/morepaolo/roundcube-pop3fetcher

**Comment by nuxwin** [comment]
@Ninos 

Last stated in the thread on our forum, the plugin is not maintained by the upstream author. Last commit is from Mar 2, 2014...

**Comment by Ninos** [comment]
I hate such shit. Wait I'll contact him, may then he should move the repository or add permissions for some users..
Otherwise I'll merge :)

**Comment by theqkash** [comment]
It won't be updated, author has forgotten this project. 

 There was several fixes by another users before, and it was not merged to this project, this time it would be the same.

I have made fork of it with fixed version of this file.

**Comment by Ninos** [comment]
@theqkash I got an invitation as contributor. I've asked for permissions for you. Please let me know if you got an invitation.

**Comment by theqkash** [comment]
@Ninos you're a magician :D

**Comment by theqkash** [comment]
@Ninos it has been merged to pop3fetcher project.

**Comment by Ninos** [comment]
Thank you! Is it maybe possible to merge also other fixes (if working fine) and/or release a new version (1.9.1 or 2.0)? I'll then use this new version :)

**Comment by theqkash** [comment]
Checked and done.

I've left only pgsql fix which has no relation with i-MSCP and I cannot check it at this time

**Comment by Ninos** [comment]
Ok updated, thx:
https://github.com/i-MSCP/plugins/commit/f23bcc2bdc79c84a09ee0907767f2046d08d1933

BTW: You have a small typo, version should be 1.9.1 instead of 1.91 :)

**Comment by theqkash** [comment]
@Ninos https://github.com/morepaolo/roundcube-pop3fetcher/releases/tag/1.9.1

Fixed, change version.txt and main php file again, sorry for that.
Thanks for reporting this mistake.

**Comment by Ninos** [comment]
Merged latest version, no stress. Thank you!

**Pull request closed without merging**
