### PR TITLE
OpenDKIM: Create folder with correct permissions

### PR DESCRIPTION
**Pull request by Backdraft007**
First create /etc/opendkim with correct permissions

### CODE REVIEW

**Comment by Ninos** [comment]
Are the permissions false per default or why you change them on the parent folder recursively?

**Comment by Backdraft007** [comment]
When the folder /etc/opendkim/keys is created the owner/group of folder /etc/opendkim is root. So the process cannot write/read their. In this case the ownership must be changed.

**Comment by Ninos** [comment]
Never had permission problems with the opendkim plugin. Also as I know the plugin only needs the keys, not the config files. Can you may be a little bit more clear why the user opendkim should also get access to the config files? Then I'll investigate.

PS: A problem scenario would also be nice or a link to the thread where someone described this problem.

**Comment by Backdraft007** [comment]
@Ninos 
I have changed it after this discussion:
http://i-mscp.net/index.php/Thread/5148-OpenDKIM/?postID=36226#post36226

**Comment by Ninos** [comment]
I'll investigate this evening and give feedback. Thanks

**Comment by Backdraft007** [comment]
Ok, you're welcome.

**Comment by Ninos** [comment]
Could confirm on Debian Jessie, thx

**Pull request merged**
